import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SessionHeader from "./components/SessionHeader";
import SessionProviderWrapper from "./components/SessionProviderWrapper";
import Sidebar from "@/app/components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-[var(--background)]`}>
        <SessionProviderWrapper>
          <div className="flex min-h-screen">
            <Sidebar />
            <main className="flex-1 flex flex-col items-center justify-center">
              <div className="card w-full max-w-6xl my-8">
                <SessionHeader />
                {children}
              </div>
            </main>
          </div>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
